name: dmltest
channels:
  - desilinguist
  - anaconda
  - prkrekel
  - defaults
  - conda-forge
dependencies:
  - numpy
  - numpy-base
  - pandas
  - py-xgboost
  - scipy
  - matplotlib
  - matplotlib-base
  - python
  - scikit-learn
  - skll

