name: DairyML
channels:
  - desilinguist
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - skll=1.5.3
  - seaborn=0.9.0
  - numpy=1.17.4
  - mlxtend=0.17.0
  - scikit-learn=0.20.1
  - py-xgboost=0.90
  - notebook
  - matplotlib=3.1.1
  - keras=2.2.4
  - python=3.6.9
  - scipy=1.3.1
  - numpy-base=1.17.4
  - hyperopt=0.2.2
  - matplotlib-base=3.1.2
  - pandas=0.25.3
  - pillow=6.2.1
  - nomkl=3.0
  - tensorflow=2.0.0=mkl_py36ha38f243_0
  - tensorflow-base=2.0.0=mkl_py36h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0


