name: dmltest
channels:
  - desilinguist
  - anaconda
  - prkrekel
  - defaults
  - conda-forge
dependencies:
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.24.1
  - py-xgboost=0.80
  - scipy=1.2.0
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - python=3.6.8
  - scikit-learn=0.20.1
  - skll=1.5.3

