name: dmltest_dec_19
channels:
  - desilinguist
  - anaconda
  - prkrekel
  - defaults
  - conda-forge
dependencies:
  - numpy=1.17.4
  - numpy-base=1.17.4
  - pandas=0.25.3
  - py-xgboost=0.90
  - scipy=1.3.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.2
  - python=3.6.9
  - scikit-learn=0.20.1
  - skll=1.5.3
  - keras=2.2.4
  - nomkl=3.0