name: DairyML
channels:
  - desilinguist
  - anaconda
  - prkrekel
  - defaults
  - conda-forge
dependencies:
  - numpy
  - numpy-base
  - pandas
  - py-xgboost
  - scipy
  - matplotlib
  - matplotlib-base
  - python
  - scikit-learn
  - skll
  - keras
  - matplotlib
  - seaborn
  - hyperopt
  - mlxtend
  - notebook
  - python=3.6
